# Generated by Django 4.2 on 2023-05-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('finalizado', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
